language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t divyanshkumar1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true divyanshkumar1/docker-react npm run test
